spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/secure_stream
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true
    locations: "classpath:db/migrate"

env:
  cors:
    allowed-origin: http://localhost:3000,http://localhost:3001
  hydra:
    admin:
      url: http://localhost:4445