spring:
  profiles:
    active: local
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: "classpath:db/migrate"

server:
  servlet:
    session:
      cookie:
        secure: true
        http-only: true

env:
  cors:
    allowed-origin: ${ALLOWED_ORIGIN}
  hydra:
    admin:
      url: ${HYDRA_ADMIN_CLIENT:http://localhost:4445}