spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/secure_stream
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
            scope: user:email
            redirectUri: http://localhost:8081/api/v1/users/social_login/code/github
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            scope: https://www.googleapis.com/auth/userinfo.profile
            redirectUri: http://localhost:8081/api/v1/users/social_login/code/google
        provider:
          github:
            authorizationUri: https://github.com/login/oauth/authorize
            tokenUri: https://github.com/login/oauth/access_token
          google:
            authorizationUri: https://accounts.google.com/o/oauth2/v2/auth
            tokenUri: https://www.googleapis.com/oauth2/v4/token

env:
  cors:
    allowed-origin: http://localhost:3000,http://localhost:3001
  webauthn:
    rp:
      id: localhost
  hydra:
    admin:
      url: http://localhost:4445
    public:
      url: http://localhost:44444
  auth-front:
    url: http://localhost:3001
  sp-front:
    url: http://localhost:3000
