spring:
  profiles:
    active: local
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: http://localhost:4445/admin/oauth2/introspect
          client-id: bd166c9a-a6ec-4e01-bcd6-f4a7e64a536f
          client-secret: tBW_irIBX7yOShRaheT7QYhweg

logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  port: 8081

env:
  cors:
    allowed-origin: ${ALLOWED_ORIGIN}
  auth-front:
    url: ${SP_FRONT_URL}
  sp-front:
    url: ${SP_FRONT_URL}