spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/secure_stream
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: "classpath:db/migrate"

env:
  cors:
    allowed-origin: http://localhost:3000,http://localhost:3001
  hydra:
    admin:
      url: http://localhost:4445